with 

source as (

    select * from {{ source('sante', 'actphys') }}

),

renamed as (

    select
        population,
        noind,
        transport_personnel,
        transport_ecole,
        tv_score,
        tv_duree,
        jvideo_score,
        jvideo_duree,
        ordi_score,
        ordi_duree,
        jeux_pleinair_nbjours,
        enfant_actif,
        eps_ouinon,
        eps_nbjours,
        eps_duree,
        club_nbjours,
        club_nb,
        activite_musculation_nbjours,
        activite_moderee_nbjours,
        activite_intense_nbjours,
        escalier_score,
        emploi_4sem,
        travail_freq_semaine,
        travail_duree,
        travail_score,
        transport_voiture_score,
        transport_public_score,
        transport_velo_score,
        transport_pied_score,
        transport_score,
        activite_balayer_score,
        activite_nettoyer_score,
        activite_aspirateur_score,
        activite_repasser_score,
        activite_vaisselle_score,
        activite_lessive_score,
        activite_jardiner_score,
        activite_tondre_score,
        activite_arroser_score,
        activite_becher_score,
        activite_bricoler_score,
        activite_marche_score,
        activite_piscine_score,
        activite_velo_score,
        activite_roller_score,
        activite_danse_salon_score,
        activite_bowling_score,
        activite_billard_score,
        activite_peche_score,
        activite_chasse_score,
        activite_loisirs_assis_score,
        activite_loisirs_debout_score,
        activite_randonnee_score,
        activite_jogging_score,
        activite_natation_score,
        activite_yoga_score,
        activite_rameur_score,
        activite_aerobic_score,
        activite_danse_moderne_score,
        activite_cyclisme_score,
        activite_tennis_score,
        activite_boxe_score,
        activite_escrime_score,
        activite_haltere_score,
        activite_athletisme_score,
        activite_ski_score,
        activite_voile_score,
        activite_canoe_score,
        activite_equitation_score,
        activite_golf_score,
        activite_tir_score,
        activite_moto_score,
        activite_musique_score,
        activite_ping_pong_score,
        activite_gym_score,
        activite_escalade_score,
        activite_alpinisme_score,
        activite_foot_score,
        activite_rugby_score,
        activite_basket_score,
        activite_hand_score,
        activite_volley_score,
        activite_hockey_score,
        activite_domloissport_duree,
        activite_domloissport_score,
        activite_moderee_score,
        activite_intense_score,
        activite_total_duree,
        activite_total_score,
        nap,
        profil_activite,
        sedentarite,
        sedentarite_duree

    from source

)

select * from renamed
