select 
    Region,
    region_text,
    class_sexe,
    class_age,
--    class_revenue,
--    tps_travail_interv,
--    situ_alim_statut, --
--    ia_statut, --
--    class_IMC, -- potentiel groupement en COUNTIF
--    statnut,
    avg(vegetarien) as perc_vegetarien,
 --   poids_modif,
    avg(class_fumeur) as perc_fumeur,
--    bmr_kcal,
--    transport_ecole, -- potentiel groupement en COUNTIF
    avg(temps_ecran) as avg_tps_ecran,
    avg(jeux_pleinair_nbjours) as avg_pleinair_nbjours,
--    avg(eps_duree) as avg_eps_duree,
--    club_nbjours,
--    club_nb,
    avg(activite_musculation_nbjours) as avg_activite_musculation_nbjours,
    avg(activite_moderee_nbjours) as avg_activite_moderee_nbjours,
    avg(activite_intense_nbjours) as avg_activite_intense_nbjours,
--    emploi_4sem,
--    travail_freq_semaine,
--    travail_duree,
--    transport_motorise,
--    transport_actif,
    avg(activite_total_duree) as avg_activite_total_duree,
--    activite_total_score,
--    nap,
--    profil_activite,
--    sedentarite,
    avg(sedentarite_duree) as avg_sedentarite_duree,
--    distributeur_sodas,
--    restaurationrapide_freq, -- potentiel groupement en COUNTIF
--    etiquette_message_nutri,
--    etiquette_effets_benefiques,
--    autoconsommation_type,
    avg(consommation_bio) as perc_consommation_bio,
--    consommation_bio_type,
--    choix_aliment_origine,
--    choix_aliment_prix,
--    choix_aliment_facilite_prepa,
--    choix_aliment_mode_prod,
--    choix_aliment_compo_nutri,
--    choix_aliment_raison_sante,
--    lieu_achat_fruits_leg,
--    lieu_achat_boulangerie,
--    lieu_achat_viandes,
--    lieu_achat_poissons_frais,
    avg(conso_cereales) as avg_conso_cereales,
    avg(conso_produits_laitiers) as avg_conso_produits_laitiers,
    avg(conso_fruits_a_coque) as avg_conso_fruits_a_coque,
    avg(conso_plats_prepares) as avg_conso_plats_prepares,
    avg(conso_matieres_grasses_ajoutees) as avg_conso_matieres_grasses_ajoutees,
    avg(conso_viandes_et_oeufs) as avg_conso_viandes_et_oeufs,
    avg(conso_charcuterie) as avg_conso_charcuterie,
    avg(conso_poissons_fruits_mer) as avg_conso_poissons_fruits_mer,
    avg(conso_fruits_legumes) as avg_conso_fruits_legumes,
    avg(conso_legumineuses) as avg_conso_legumineuses,
    avg(conso_produits_sucres) as avg_conso_produits_sucres,
    avg(conso_boissons_sans_alcool) as avg_conso_boissons_sans_alcool,
    avg(conso_alcool) as avg_conso_alcool
--    reco_fruits_legumes,
--    reco_fruits_a_coque,
--    reco_legumineuses,
--    reco_cereales,
--    reco_produits_laitiers,
 --   reco_viandes_et_oeufs,
--    reco_poissons_fruits_mer,
--    reco_charcuterie,
--    reco_matieres_grasses_ajoutees,
--    reco_produits_sucres,
--    reco_alcool

from {{ ref('INCA_indiv_join') }}
group by 
    Region,
    region_text,
    class_sexe,
    class_age
order by 
    Region,
    region_text,
    class_sexe,
    class_age