version: 2

sources:
  - name: sante
    schema: SANTE2
    tables:
      - name: indiv
        identifier: description-indiv
        description: individu 
        columns:
        - name: NOMEN
          description: Numéro de ménage 

  - name: sante
    schema: SANTE2
    tables:
      - name: sedent
        identifier: 'actphys-sedent'
        description: Cette table contient les données des questionnaires auto-administrés (pour les adultes 18-79 ans) 
        et face-à-face (pour les enfants 3-17 ans) relatifs au volet « Sédentarité, activité physique et loisirs ». 
        Il n’y a pas de données relatives à cette thématique pour les enfants de 0-35 mois. 
        columns:
        - name: POPULATION
          description: Pop1 Individu pour les enfants de 3-17 ans et Pop2 Individu pour les adultes de 18-79 ans
#          tests:
#          - unique
#          - not_null

#### Example cours
#      - name: parcel_product 
#        identifier: raw_cc_parcel_product 
#        description: parcel_product of Circle
#        tests:
#          - unique:
#              column_name: "ParCEL_id || '-' || Model_mAME"
#          - not_null:
#              column_name: "ParCEL_id || '-' || Model_mAME"
#        columns:
#        - name: parcel_id
#          description: primary key for this table (Integer ID of parcel)